In [4]:
class PirmojiKlase():
    def __init__(self) -> None:
        print('konstruktorius sukurtas')

a= PirmojiKlase()

konstruktorius sukurtas

In [5]:
class PirmojiKlase():
    def __init__(self) -> None:
        print('konstruktorius sukurtas')
    
    def __del__(self):
        print('destruktorius veikia')
        
a= PirmojiKlase()
del a

konstruktorius sukurtas
destruktorius veikia

In [14]:
class PirmojiKlase():
    def __init__(self) -> None:
        self.X=15


a=PirmojiKlase()

print(a.X)
a.X=30

print(a.X)

15
30

In [18]:
class PirmojiKlase():
    def __init__(self) -> None:
        self.X=15
    
    def getX(self):
        print(self.X)
    
    def keiciamX(self):
        self.X=self.X*2
        


a=PirmojiKlase()
a.getX()
a.keiciamX()
a.getX()

15
30

In [20]:
import time
class Tarakonas():
    def __init__(self) -> None:
        print('išsirito tarakonas')
        self.gimtadienis=time.time()
    def __del__(self):
        print('Tarakonas mirė. Jis gyveno:',time.time()-self.gimtadienis)
Rudis=Tarakonas()
time.sleep(0.7)
Juodis=Tarakonas()
time.sleep(0.7)
Pilkis=Tarakonas()
print(Rudis.gimtadienis)
print(Juodis.gimtadienis)
print(Pilkis.gimtadienis)
del Rudis
del Juodis
del Pilkis

išsirito tarakonas
Tarakonas mirė. Jis gyveno: 32.023568868637085
išsirito tarakonas
Tarakonas mirė. Jis gyveno: 32.02310395240784
išsirito tarakonas
Tarakonas mirė. Jis gyveno: 32.022924184799194
1721234686.790143
1721234687.4912407
1721234688.1917195
Tarakonas mirė. Jis gyveno: 1.4015765190124512
Tarakonas mirė. Jis gyveno: 0.7004787921905518
Tarakonas mirė. Jis gyveno: 0.0

In [1]:
failo_vardas = 'V1670_2024-04-24.dat'

failas = open(failo_vardas, mode='r', encoding='utf-8')
turinys = failas.readlines()
failas.close()

list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]

for i in turinys[3:-1]:
    eilute=i.split()
    if eilute[0]=='Tamsa':
        break
    list1.append(float(eilute[0]))
    list2.append(float(eilute[1]))
    list3.append(float(eilute[2]))
    list4.append(float(eilute[3]))
    list5.append(float(eilute[4]))
    list6.append(eilute[5])   

print(list5)

[4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 4.07, 4.07, 3.86, 3.86, 4.07, 4.07, 3.73, 3.73, 4.27, 4.27, 3.73, 3.73, 3.73, 3.73, 3.73, 3.73, 3.79, 3.79, 3.79, 3.86, 3.86, 3.86, 3.86, 4.07, 4.07, 4.07, 3.86, 3.86, 3.86, 3.86, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0]

In [16]:
import os
import glob

os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")
dat_failai = glob.glob('*.dat')


list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]

for f in dat_failai:
    
    failas = open(f, mode='r', encoding='utf-8')
    turinys = failas.readlines()
    failas.close()
    
    for i in turinys[3:-1]:
        eilute=i.split()
        if eilute[0]=='Tamsa':
            break
        list1.append(float(eilute[0]))
        list2.append(float(eilute[1]))
        list3.append(float(eilute[2]))
        list4.append(float(eilute[3]))
        list5.append(float(eilute[4]))
        list6.append(eilute[5])   

print(list5)

[4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 4.07, 4.07, 3.86, 3.86, 4.07, 4.07, 3.73, 3.73, 4.27, 4.27, 3.73, 3.73, 3.73, 3.73, 3.73, 3.73, 3.79, 3.79, 3.79, 3.86, 3.86, 3.86, 3.86, 4.07, 4.07, 4.07, 3.86, 3.86, 3.86, 3.86, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.0, 4.07, 4.07, 3.93, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 3.93, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07]

In [20]:
import os
import glob

os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")
dat_failai = glob.glob('*.dat')

def is_float(string):
    try:
        float(string)
        return True
    except ValueError:
        return False

list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]

for f in dat_failai:
    
    failas = open(f, mode='r', encoding='utf-8')
    turinys = failas.readlines()
    failas.close()
    
    for i in turinys:
        eilute=i.split()
        if is_float(eilute[0]):
            list1.append(float(eilute[0]))
            list2.append(float(eilute[1]))
            list3.append(float(eilute[2]))
            list4.append(float(eilute[3]))
            list5.append(float(eilute[4]))
            list6.append(eilute[5])   

print(list5)

[4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 4.07, 4.07, 3.86, 3.86, 4.07, 4.07, 3.73, 3.73, 4.27, 4.27, 3.73, 3.73, 3.73, 3.73, 3.73, 3.73, 3.79, 3.79, 3.79, 3.86, 3.86, 3.86, 3.86, 4.07, 4.07, 4.07, 3.86, 3.86, 3.86, 3.86, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.0, 4.07, 4.07, 3.93, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 3.93, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.0, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 3.93, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.07, 4.07, 4.07, 3.93, 3.93, 4.0, 4.0, 4.0, 4.0, 4.07, 4.07]

In [24]:
import os
import glob

os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")
dat_failai = glob.glob('*.dat')
print(dat_failai)
txt_failai = glob.glob('*.txt')
print(txt_failai)

def is_float(string):
    try:
        float(string)
        return True
    except ValueError:
        return False
    
def is_empty(list, nr):
    try:
        len(list[nr]) >0
        return True
    except IndexError:
        return False



def atrenkame_stulpeli(f, st):
    
    failas = open(f, mode='r', encoding='utf-8')
    turinys = failas.readlines()
    failas.close()
    
    for i in range(0, len(turinys)):
        turinys[i]=turinys[i].replace(';','').replace(',', '.').split()

    ats=[]
    
    if len(turinys[0]) >= stulpelio_nr and stulpelio_nr>0:
        for i in turinys: 
            if is_empty(i, 0):
                if is_float(i[0]) and is_float(i[1]):
                    if is_float(i[st-1]):
                        ats.append(float(i[st-1]))
                    else:
                        ats.append(i[st-1])       
    else:
        print('ivedete per dideli arba per maza stulpelio nr')
    return ats


list=[]
stulpelio_nr=2
list=atrenkame_stulpeli(dat_failai[1], stulpelio_nr)
print(list)

['V1670_2024-04-24.dat', 'V1671_2024-04-24.dat', 'V1672(CB)_2024-04-24.dat', 'V1672(DCM)_2024-04-24.dat']
['Skaityk.txt', 'V1244S_20210409_14h56.txt', 'V1296OLD_20210409_18h24.txt', 'V1296S_20210409_15h31.txt', 'V1296T_20210409_16h20.txt']
[48.0, 48.0, 48.0, 12.0, 60.0, 12.0, 132.0, 84.0, 24.0, 60.0, 36.0, 36.0, 60.0, 36.0, 0.0, 48.0, 48.0, 84.0, 24.0, 72.0, 36.0, 36.0, 48.0, 36.0, 36.0, 24.0, 24.0, 36.0, 36.0, 96.0, 48.0, 48.0, 36.0, 60.0, 48.0, 144.0, 60.0, 36.0, 132.0, 72.0, 72.0, 36.0, 60.0, 72.0, 60.0, 48.0, 48.0, 36.0, 12.0, 72.0, 168.0, 108.0, 96.0, 60.0, 24.0, 60.0, 192.0, 72.0, 120.0, 24.0, 60.0, 84.0, 108.0, 72.0, 120.0, 84.0, 120.0, 60.0, 96.0, 72.0, 144.0, 84.0, 120.0, 108.0, 144.0, 132.0, 120.0, 120.0, 96.0, 288.0, 168.0, 144.0, 240.0, 276.0, 252.0, 252.0, 204.0, 156.0, 264.0, 288.0, 264.0, 312.0, 312.0, 216.0, 360.0, 324.0, 420.0, 432.0, 552.0, 552.0, 588.0, 588.0, 684.0, 528.0, 696.0, 780.0, 960.0, 864.0, 1296.0, 1236.0, 1152.0, 1368.0, 1284.0, 1308.0, 1812.0, 2160.0, 2628.0, 2628.0, 2712.0, 2100.0, 2772.0, 2940.0, 3036.0, 4404.0, 4332.0, 4092.0, 5616.0, 5508.0, 5100.0, 6180.0, 6432.0, 6756.0, 8772.0, 7428.0, 7632.0, 9672.0, 8520.0, 8268.0, 10452.0, 10332.0, 11016.0, 13320.0, 12648.0, 13464.0, 15540.0, 14928.0, 14808.0, 19392.0, 19704.0, 19404.0, 21408.0, 20472.0, 20376.0, 22200.0, 22068.0, 23964.0, 29136.0, 28596.0, 26184.0, 30036.0, 28608.0, 29856.0, 34788.0, 38100.0, 38928.0, 42072.0, 40716.0, 39240.0, 41544.0, 39708.0, 39768.0, 49704.0, 53364.0, 50376.0, 54648.0, 52740.0, 50208.0, 58980.0, 57948.0, 63084.0, 74244.0, 70404.0, 67656.0, 73176.0, 70548.0, 69972.0, 75240.0, 82404.0, 85200.0, 99984.0, 94800.0, 92448.0, 98544.0, 93756.0, 95808.0, 114684.0, 119136.0, 117708.0, 125268.0, 120660.0, 117552.0, 124452.0, 124080.0, 137868.0, 150744.0, 148836.0, 143868.0, 151356.0, 145944.0, 143472.0]

In [15]:
import os
import glob

os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")
txt_failai = glob.glob('*.txt')
print(txt_failai)

failas = open(txt_failai[2], mode='r', encoding='utf-8')
turinys = failas.readlines()
failas.close()
    
for i in range(0, len(turinys)):
    turinys[i]=turinys[i].replace(';','').replace(',', '.').split()
    
print(turinys[0])
print(turinys[1])
print(turinys[5])
list=['a', '1', '5.32', '45', 'gdh4']

a=turinys[1]

def is_float(string):
    try:
        float(string)
        return True
    except ValueError:
        return False
    

    
def is_empty(list, nr):
    try:
        len(list[nr]) >0
        return True
    except IndexError:
        return False
    
if is_empty(a, 0):
    if is_float(a[0]):
        print('floatas')
    else:
        print('nefloatas')
else:
    print('tuscias')

    
#is_float(a[1])

['Skaityk.txt', 'V1244S_20210409_14h56.txt', 'V1296OLD_20210409_18h24.txt', 'V1296S_20210409_15h31.txt', 'V1296T_20210409_16h20.txt']
['Eil.Nr.', 'hv.', '[eV]', 'Cor(N/Le)', '[min-1]Cor(N/Lq)', '[min-1]Ni', 'vertė', 'Ni/min.', 'Sqrt(Ni)', 'Dujos', 'E.light', 'Q.Light', 'Laikas']
[]
['3', '4.5', '73', '65', '9', '54', '7', '226', '0.740906', '0.83348', '16:24:08']
tuscias