In [26]:
import datetime

data_in='2001-08-12'
data= datetime.datetime.strptime(data_in, "%Y-%m-%d")

data_n=datetime.datetime.now()

skirtumas = data_n - data

print(round(skirtumas.total_seconds()/3600))

201140

In [28]:
import datetime

data_in='Sep-08-1997'
data= datetime.datetime.strptime(data_in, "%b-%d-%Y")

data_n=datetime.datetime.now()

skirtumas = data_n - data

print(skirtumas)

9814 days, 19:37:00.405807

In [91]:
import os
import glob
import datetime

os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")

def naftos_kaina(data):
    
    dt= datetime.datetime.strptime(data, "%Y-%m-%d")
    
    failas = open('BrentOilPrices.csv', mode='r', encoding='utf-8')
    turinys = failas.readlines()
    failas.close()
    
    for i in range(1, len(turinys)):
        turinys[i-1]=turinys[i].split(',')
        turinys[i-1][0]=datetime.datetime.strptime(turinys[i-1][0], "%d-%b-%y")

    tf=False
    for i in turinys:
        if i[0] == dt:
            return i[1]
            tf=True
    if tf== False:
        return -42

data_in='2001-12-11'
print('naftos kaina ', data_in, 'diena buvo ', naftos_kaina(data_in))

data_in='2020-01-31'
print('naftos kaina ', data_in, 'diena buvo ', naftos_kaina(data_in))

data_in='2020-02-01'
print('naftos kaina ', data_in, 'diena buvo ', naftos_kaina(data_in))

naftos kaina  2001-12-11 diena buvo  17.61

naftos kaina  2020-01-31 diena buvo  57.77

naftos kaina  2020-02-01 diena buvo  -42

In [97]:
import os
import glob
import datetime

os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")

def naftos_intervalas(data1, data2):
    
    dt1= datetime.datetime.strptime(data1, "%Y-%m-%d").date()
    dt2= datetime.datetime.strptime(data2, "%Y-%m-%d").date()
    
    failas = open('BrentOilPrices.csv', mode='r', encoding='utf-8')
    turinys = failas.readlines()
    failas.close()
    
    for i in range(1, len(turinys)):
        turinys[i-1]=turinys[i].split(',')
        turinys[i-1][0]=datetime.datetime.strptime(turinys[i-1][0], "%d-%b-%y").date()
    
    turinys.pop(-1)
    
    ats=[]
    for i in turinys:
        if dt1 <= i[0] <= dt2:
            ats.append(i)

    ats1, ats2 = [], []
    for i in ats:
        ats1.append(i[0])
        ats2.append(i[1][:-1])
        
    return ats1, ats2
        
data_in1='2001-12-11'
data_in2='2002-04-30'
answD, answK=naftos_intervalas(data_in1, data_in2)
    
for i in range (0, len(answD)):
    print(answD[i], answK[i])

2001-12-11 17.61
2001-12-12 18.13
2001-12-13 17.8
2001-12-14 18.54
2001-12-17 18.58
2001-12-18 18.51
2001-12-19 19.03
2001-12-20 18.87
2001-12-21 18.73
2001-12-24 18.65
2001-12-27 18.87
2001-12-28 19.77
2001-12-31 19.35
2002-01-02 20.13
2002-01-03 20.47
2002-01-04 21.2
2002-01-07 21.08
2002-01-08 21.03
2002-01-09 20.21
2002-01-10 19.71
2002-01-11 20.08
2002-01-14 18.89
2002-01-15 18.86
2002-01-16 18.5
2002-01-17 18.2
2002-01-18 18.17
2002-01-21 18.32
2002-01-22 18.7
2002-01-23 18.89
2002-01-24 18.91
2002-01-25 19.04
2002-01-28 19.74
2002-01-29 19.26
2002-01-30 18.71
2002-01-31 19.07
2002-02-01 19.7
2002-02-04 20.26
2002-02-05 19.9
2002-02-06 19.97
2002-02-07 19.42
2002-02-08 20.01
2002-02-11 20.08
2002-02-12 21.75
2002-02-13 21.41
2002-02-14 20.97
2002-02-15 20.76
2002-02-18 20.12
2002-02-19 20.18
2002-02-20 19.44
2002-02-21 20.21
2002-02-22 20.14
2002-02-25 19.78
2002-02-26 19.95
2002-02-27 20.73
2002-02-28 20.73
2002-03-01 21.83
2002-03-04 21.59
2002-03-05 22.25
2002-03-06 22.11
2002-03-07 23.1
2002-03-08 22.32
2002-03-11 23.14
2002-03-12 22.7
2002-03-13 23.6
2002-03-14 23.76
2002-03-15 23.9
2002-03-18 23.8
2002-03-19 24.51
2002-03-20 24.78
2002-03-21 24.25
2002-03-22 24.83
2002-03-25 24.75
2002-03-26 24.6
2002-03-27 25.13
2002-03-28 25.34
2002-03-29 25.34
2002-04-01 26.06
2002-04-02 26.97
2002-04-03 26.72
2002-04-04 26.97
2002-04-05 25.39
2002-04-08 26.36
2002-04-09 25.48
2002-04-10 25.13
2002-04-11 24.22
2002-04-12 23.25
2002-04-15 23.39
2002-04-16 24.03
2002-04-17 25.26
2002-04-18 25.9
2002-04-19 25.86
2002-04-22 25.96
2002-04-23 26.26
2002-04-24 26.2
2002-04-25 26.47
2002-04-26 26.32
2002-04-29 26.85
2002-04-30 26.98

In [108]:
import os
import glob

def veiksmai(txt):
    st1= txt[0: 2]
    st2 = txt[-2:]
    veik=txt.replace(st1, '').replace(st2, '')

    os.chdir(r"C:\Users\pauli\Desktop\DataScienceNotebooks\DATA")
    failas = open('fpc.csv', mode='r', encoding='utf-8')
    turinys = failas.readlines()
    failas.close()
    
    for i in range (0, len(turinys)):
        turinys[i] = turinys[i].split(',')
        
    turinys.pop(0)
    
    for i in turinys:
        ats[0]=

veiksmai('c2 + c4')

#eval()