In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestRegressor
# Load dataset
data = load_iris()
X, y = data.data, data.target
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Initialize and train the RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
# Make predictions
y_pred = rf.predict(X_test)
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred) 
print(f'Accuracy:{accuracy}')

Accuracy:1.0

In [26]:
import pandas as pd
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import LabelEncoder

In [131]:
df = pd.read_csv(r"C:\Users\pauli\Downloads\interval_data.csv")

In [134]:
df.head()

,obs_time_utc,air_temperature,feels_like_temperature,wind_speed,wind_gust,wind_direction,cloud_cover,sea_level_pressure,relative_humidity,precipitation,condition_code,temp_skirtumas
0,2024-12-29 00:00:00,1.6,-0.2,1.7,5.3,222,100.0,1025.7,98,0.0,cloudy,0.0
1,2024-12-29 01:00:00,1.5,-0.6,1.9,3.7,246,100.0,1025.3,99,0.0,cloudy,0.1
2,2024-12-29 02:00:00,1.4,-1.0,2.1,4.7,242,100.0,1025.0,98,0.0,cloudy,0.1
3,2024-12-29 03:00:00,1.2,-1.9,2.8,6.1,252,100.0,1024.7,98,0.0,cloudy,0.2
4,2024-12-29 04:00:00,0.9,-1.2,1.8,4.5,220,100.0,1024.1,100,0.0,cloudy,0.3

In [136]:
sar = df['air_temperature'].to_list()
Tskirtumas=[0]

for i in range(0, len(df)-1):
    Tskirtumas.append(round(sar[i]-sar[i+1], 2))

In [137]:
print(Tskirtumas)

[0, 0.1, 0.1, 0.2, 0.3, 0.3, 0.0, 0.3, 0.3, -0.2, 0.1, -0.2, -0.2, -0.3, -0.4, -0.4, -0.6, 0.0, 0.4, 0.0, 0.2, 0.2, 0.0, -0.1, -0.1, 0.1, -0.1, 0.0, -0.2, -0.6, -0.3, 0.1, -0.1, 0.0, -0.2, 0.0, -0.1, 0.1, -0.1, -0.1, -0.2, -0.3, -0.1, 0.2, 0.0, -0.1, -0.2, 0.1, 0.1, 0.6, -0.1, -0.4, -0.2, -0.1, -0.1, -0.1, -0.2, -0.2, -0.3, -0.4, -0.4, 0.2, 0.5, 0.7, 0.2, 0.1, 0.2, -0.2, 0.6, -0.9, 0.1, 0.6, 0.5, 0.9, 0.4, -0.2, 0.2, 0.3, 0.1, -0.2, -0.7, -0.3, 0.0, 0.0, -0.1, 0.0, 0.1, -0.2, -0.2, -0.1, -0.3, -0.3, -0.5, -0.2, 0.3, 0.3, -0.1, -0.1, -0.3, -0.4, -0.1, -0.2, 0.1, -0.3, 0.1, 0.0, 0.2, -0.3, 2.6, 0.7, 0.5, 0.2, 0.2, 0.5, 0.7, 0.9, 0.6, 0.0, 0.0, -0.1, -0.5, -0.3, 0.1, 0.2, 1.0, -0.1, 0.5, -0.1, -0.4, -0.2, -0.6, -0.4, -0.2, 0.4, 0.9, -0.9, 0.2, 0.6, -0.1, 0.1, -0.3, 0.3, -0.6, 0.5, 0.4, 0.1, 0.1, -0.5, 0.6, 0.5, 0.8, -0.2, -0.1, -0.4, -0.6, -0.3, -0.5, -0.6, 0.0, 0.8, 0.6, 0.4, 0.5, 0.2, 0.1, 1.0, 0.1, 0.6]

In [138]:
df['temp_skirtumas']= Tskirtumas

In [139]:
df['obs_time_utc'] = df['obs_time_utc'].apply(lambda x: int(x.split(' ')[1].split(':')[0]))

In [140]:
df['condition_code'] = LabelEncoder().fit_transform(df['condition_code'])
condition_code = dict(zip(df['condition_code'], df['condition_code']))

In [141]:
df=df.dropna()

In [32]:
len(df)

162

In [28]:
print(condition_code)

{1: 1, 3: 3, 4: 4, 7: 7, 2: 2, 5: 5, 8: 8, 6: 6, 10: 10, 9: 9, 11: 11, 0: 0}

In [175]:
X= df.drop(columns=['air_temperature', 'feels_like_temperature', 'temp_skirtumas', 'condition_code' ])
y=df['air_temperature']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=37)

fit = LinearRegression().fit(X_train, y_train)

pred = fit.predict(X_test)
fit.score(X_test, y_test)*100.0

50.38803129846505

In [176]:
pred = [round(num, 2) for num in pred]
py_list = [float(num) for num in pred]
print(py_list)

[2.0, 1.9, 3.68, 0.4, 3.37, 3.06, -1.55, 3.86, 1.96, 3.01, 2.06, 3.33, -0.22, -1.19, 0.29, 0.55, 3.51, 1.32, 2.13, 1.33, 3.71, 2.35, 2.98, 1.61, 1.07, -1.08, -1.37, 1.95, -0.96, -0.14, -3.54, 2.88, 3.98, 3.3, -2.2, 0.37, 1.75, 2.69, -4.15, 0.45, 0.9, -3.77, -0.95, 2.01, -1.75, 1.48, -0.21, -4.79, 0.8]

In [177]:
rf = RandomForestRegressor(n_estimators=70, random_state=35)
rf.fit(X_train, y_train)
# Make predictions
y_pred = rf.predict(X_test)
# Evaluate accuracy
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f'Mean Absolute Percentage Error: {mape}%')

Mean Absolute Percentage Error: 74.46249501989077%

In [178]:
print(y_pred)

[ 1.48142857  4.15285714  3.21714286  4.45857143  2.91428571  2.80142857
 -1.74857143  3.18857143  1.11285714  2.51285714  3.04571429  3.53857143
 -2.08714286 -3.17857143  2.36       -0.87571429  3.74857143  1.54142857
  1.47428571  1.67        3.75142857  2.90571429  3.20714286  1.43428571
  2.17       -2.41428571 -0.54285714  1.28285714 -1.88       -2.37142857
 -3.79285714  3.23428571  3.18571429  3.19       -2.76571429  2.00714286
  3.52285714  1.41857143 -2.64        2.09857143  1.94428571 -3.30285714
 -1.26714286  2.87285714 -3.39        2.8        -0.20571429 -2.43714286
  1.46285714]

In [193]:
dt_regressor = DecisionTreeRegressor(random_state=35)

dt_regressor.fit(X_train, y_train)

y_pred = dt_regressor.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
# print(f"R-squared: {r2}")
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f'Mean Absolute Percentage Error: {mape}%')

Mean Squared Error: 2.623673469387755
Mean Absolute Percentage Error: 77.57673801918477%

In [202]:
X_test.iloc[1]

obs_time_utc           11.0
wind_speed              6.6
wind_gust              13.4
wind_direction        218.0
cloud_cover           100.0
sea_level_pressure    993.2
relative_humidity      87.0
precipitation           0.1
Name: 107, dtype: float64

In [211]:
X_train

,obs_time_utc,wind_speed,wind_gust,wind_direction,cloud_cover,sea_level_pressure,relative_humidity,precipitation
81,9,6.0,12.2,216,100.0,1006.2,90,0.0
97,1,5.6,13.0,220,100.0,995.6,90,0.4
119,23,2.1,4.2,215,100.0,1003.5,93,0.0
167,23,4.5,9.1,214,88.0,1013.5,84,0.0
79,7,5.3,10.3,214,100.0,1007.2,92,0.0
...,...,...,...,...,...,...,...,...
128,8,5.0,9.6,216,88.0,1002.6,86,0.0
28,4,4.0,7.3,209,100.0,1016.8,100,0.0
82,10,5.5,11.9,216,100.0,1005.2,93,0.0
113,17,6.0,13.3,271,100.0,997.2,89,0.0
149,5,8.2,16.5,283,100.0,999.0,69,0.0

In [230]:
columns = X_train.columns
X_new = [[14, 6.0, 12.2, 216, 100, 1006, 90, 0]]
X_new_df = pd.DataFrame(X_new, columns=columns)

spej = dt_regressor.predict(X_new_df)
print(spej)

[2.4]

In [212]:
spej

array([-1.])

In [184]:
X_test

,obs_time_utc,wind_speed,wind_gust,wind_direction,cloud_cover,sea_level_pressure,relative_humidity,precipitation
3,3,2.8,6.1,252,100.0,1024.7,98,0.0
107,11,6.6,13.4,218,100.0,993.2,87,0.1
38,14,5.4,11.1,237,100.0,1014.9,98,0.0
102,6,6.5,13.6,219,100.0,994.0,82,0.0
72,0,6.1,11.1,209,100.0,1013.5,99,0.0
87,15,5.2,10.3,217,100.0,1002.9,96,0.0
154,10,7.1,15.5,292,100.0,1005.9,69,0.0
89,17,6.6,12.5,214,100.0,1001.4,96,0.2
6,6,3.1,7.0,214,100.0,1023.3,100,0.0
29,5,3.3,7.6,239,100.0,1017.2,100,0.0
92,20,6.7,13.3,210,100.0,998.2,89,0.0
43,19,4.5,9.4,229,100.0,1014.7,99,0.0
117,21,1.5,3.8,250,88.0,1002.9,89,0.0
148,4,7.1,15.3,280,88.0,997.8,71,0.0
65,17,2.8,6.5,262,100.0,1017.4,89,0.0
120,0,2.7,4.2,211,100.0,1003.4,94,0.0
46,22,4.8,10.9,228,100.0,1013.9,98,0.2
4,4,1.8,4.5,220,100.0,1024.1,100,0.0
10,10,3.8,7.4,208,100.0,1022.2,100,0.0
2,2,2.1,4.7,242,100.0,1025.0,98,0.0
54,6,5.2,11.4,245,100.0,1013.0,97,0.2
85,13,5.2,10.5,212,100.0,1003.8,94,0.0
33,9,4.9,10.4,222,100.0,1016.0,98,0.0
5,5,2.9,5.5,214,100.0,1023.8,100,0.0
80,8,6.1,11.8,207,100.0,1006.4,89,0.0
155,11,6.7,12.8,288,88.0,1007.1,74,0.0
131,11,3.0,7.4,227,100.0,1002.6,83,0.0
18,18,3.5,6.5,211,88.0,1019.8,100,0.0
130,10,3.8,8.4,227,88.0,1002.6,84,0.0
156,12,7.3,12.9,288,88.0,1008.2,77,0.0
164,20,3.8,6.6,229,0.0,1013.2,83,0.0
141,21,4.8,8.7,186,100.0,997.3,97,0.8
88,16,6.5,12.3,213,100.0,1002.0,97,0.1
50,2,5.0,11.7,233,100.0,1013.1,97,0.0
157,13,6.4,14.2,284,88.0,1009.1,70,0.0
129,9,4.5,9.6,224,100.0,1002.9,87,0.0
98,2,6.5,13.1,224,100.0,995.0,87,0.0
23,23,3.1,6.8,230,100.0,1019.1,100,0.0
158,14,5.2,13.3,274,50.0,1010.2,68,0.0
100,4,5.7,14.5,223,100.0,994.4,82,0.0
75,3,5.1,11.2,223,100.0,1010.1,89,0.0
163,19,3.0,6.7,237,0.0,1012.9,82,0.0
112,16,5.6,10.0,242,88.0,996.2,79,0.0
84,12,4.9,9.1,213,100.0,1004.4,94,0.0
153,9,7.2,15.1,293,88.0,1004.9,69,0.0
142,22,4.7,10.4,228,100.0,997.0,88,0.3
126,6,3.4,7.2,190,75.0,1002.9,92,0.0
161,17,3.0,6.7,241,0.0,1012.3,78,0.0
78,6,5.4,10.3,217,100.0,1007.9,89,0.0

In [171]:
print(y_pred)

[ 1.5  4.7  3.   4.8  1.6  2.4 -2.5  3.7  1.8  2.6  3.2  3.7 -1.9 -3.9
  3.8 -1.   4.1  0.3  1.8  1.5  3.7  2.4  3.3  0.3  1.3 -0.4 -1.4  1.6
 -2.2 -0.4 -4.9 -1.9  2.4  3.5 -0.4 -1.9  4.5  1.4 -0.4  1.6  1.6 -3.5
  1.   2.4 -3.7 -1.9  2.  -2.6  1.4]

In [174]:

df5 = pd.read_csv(r"C:\Users\pauli\Downloads\interval_data(1).csv")

In [180]:
df5['obs_time_utc'] = df5['obs_time_utc'].apply(lambda x: int(x.split(' ')[1].split(':')[0]))
df5=df5.dropna()